services:
    sio_test:
        user: app
        build:
            context: .
            args:
                USER_ID: ${USER_ID:-1000}
        ports:
            - "8337:8337"
        volumes:
            - .:/app:rw
        environment:
            - APP_ENV=dev
        networks:
            - sio
    db:
        image: mysql:8.0.33
        ports:
            - "8002:3306"
        environment:
            MYSQL_ROOT_PASSWORD: rootsecret
            MYSQL_DATABASE: dbname
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: secret
        networks:
            - sio
networks:
    sio: